#!/bin/sh
echo "// Automatically generated by $0"
echo 'class Main'
echo '{'
echo '    static function main()'
echo '    {'
echo '        var r = new haxe.unit.TestRunner();'

for f in t/*Test.hx; do
    class=`echo $f | sed 's/^t\/\|\.hx$//g'`
    echo "        r.add(new $class());"
done

echo '        r.run();'
echo '    }'
echo '}'
